### ISSUE TITLE
prefix all functions with jd_ ?

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac-c#3]
https://github.com/microsoft/jacdac-c/blob/052213885e2cfe9158869d22dd36b31206835513/inc/interfaces/core/jd_app.h#L3

**Comment by jamesadevine** [comment]
Probably a good idea, yes. I assume there is some sort of C library convention we should follow? At the moment though "jd_" is prefixed to "library" calls. We should use a different name prefix for low-level apis: "__jd_"

**Comment by pelikhan** [comment]
Just start everything with ``jd_``, then maybe ``jd_ll_``

**Comment by pelikhan** [comment]
same for an constants ``#define JD_`` ... we want to be as consistent and conflict free as possible.

**Comment by jamesadevine** [comment]
Okie dokie, this is the first cut. Let me merge into jacdac-tiny first please.

**Comment by mmoskal** [comment]
All exported symbols should be `jd_*` or `JD_*`. I guess I would prefer `_jd_*` for internals, `_ll_` suggests you can still call them, they are just low level.

As per C standard you cannot start names with `_`, but everyone does it anyways. I would avoid double underscore though.

**Comment by jamesadevine** [comment]
👍 for the underscore prefix!
